SYNOPTIC_WINDOW_WIDTH = 684
SYNOPTIC_WINDOW_HEIGHT = 383

UNDER_CAS_WINDOW_WIDTH = 340
UNDER_CAS_WINDOW_HEIGHT = 192

ADI_WINDOW_WIDTH = 684
ADI_WINDOW_HEIGHT = 2*383

PDU_WINDOW_WIDTH = 1024
PDU_WINDOW_HEIGHT = 768

WEB_INTERFACE_PORT = 8800

# connect to master xplane plugin
XP_MASTER_HOST = "127.0.0.1"
XP_MASTER_PORT = 51000

# native xplane udp port to send to
XP_MASTER_UDP_PORT = 49000
UDP_LOCAL_PORT = 62223

# monitor id in Windows for brightness control
LEFT_MONITOR_ID = 0
RIGHT_MONITOR_ID = 1
MIDDLE_UP_MONITOR_ID = 2
MIDDLE_DOWN_MONITOR_ID = 3
MINI_MONITOR_ID = 4
